[package]
name = "grim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
complot = { version = "0.3.3", optional = true }
crseo = "0.3.0"
dos-actors = { version = "0.1.6", features = ["ceo", "apache-arrow"] }
tokio = { version = "1.18.2", features = ["rt-multi-thread"] }
