Resources:
  CFDLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        EbsOptimized: false
        KeyName: awsohio
        UserData:
          Fn::Base64:
            !Sub
            - |
                MIME-Version: 1.0
                Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

                --==MYBOUNDARY==
                Content-Type: text/cloud-config; charset="us-ascii"
                
                runcmd:
                  - amazon-linux-extras install -y lustre2.10
                  - mkdir -p /fsx
                  - mount -t lustre -o defaults,_netdev,flock,user_xattr,noatime ${fsx_id}.fsx.us-east-2.amazonaws.com@tcp:/${mount_name} /fsx 
                  
                --==MYBOUNDARY==--
            - fsx_id: "fs-0d71b7c2f779ed997"
              mount_name: "j222dbmv"
      LaunchTemplateName: CFDTemplate
  CFDCompute:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: CFDCompute
      ComputeResources: 
        AllocationStrategy: BEST_FIT
        DesiredvCpus: 32
        Ec2Configuration:
          - ImageType: ECS_AL2
        Ec2KeyPair: awsohio
        InstanceRole: arn:aws:iam::378722409401:instance-profile/ecsInstanceRole
        InstanceTypes:
          - optimal
        LaunchTemplate:
          LaunchTemplateId: !Ref CFDLaunchTemplate
          Version: $Default
        MaxvCpus: 256
        MinvCpus: 0
        SecurityGroupIds:
          - sg-184f0173
        Subnets:
          - subnet-a9a566d3
        Type: EC2
      ServiceRole: arn:aws:iam::378722409401:role/service-role/AWSBatchServiceRole
      State: ENABLED
      Type: MANAGED
  CFDJobQueue:
    Type: AWS::Batch::JobQueue
    Properties: 
      ComputeEnvironmentOrder: 
        - ComputeEnvironment: !Ref CFDCompute
          Order: 1
      Priority: 1
      JobQueueName: CFDJobs
      State: ENABLED
  CFDJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties: 
      ContainerProperties: 
        Command:
          - /usr/local/bin/asm_temperature
        Image: 378722409401.dkr.ecr.us-east-2.amazonaws.com/gmto.im/cfdminer:latest
        MountPoints:
          - ContainerPath: /fsx
            SourceVolume: fsx
        ResourceRequirements:
          - Type: VCPU
            Value: '32'
          - Type: MEMORY
            Value: '10240'
        Volumes:
          - Host:
              SourcePath: /fsx
            Name: fsx
      JobDefinitionName: CFDJob
      PlatformCapabilities: 
        - EC2
      Type: container
