Resources:
  GRIMLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        EbsOptimized: false
        KeyName: awsoregon
        UserData:
          Fn::Base64:
            !Sub
            - |
                MIME-Version: 1.0
                Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

                --==MYBOUNDARY==
                Content-Type: text/cloud-config; charset="us-ascii"
                
                runcmd:
                  - amazon-linux-extras install -y lustre2.10
                  - mkdir -p /fsx
                  - mount -t lustre -o defaults,_netdev,flock,user_xattr,noatime ${fsx_id}.fsx.us-west-2.amazonaws.com@tcp:/${mount_name} /fsx 
                  
                --==MYBOUNDARY==--
            - fsx_id: "fs-0e6759f50ff7a310c"
              mount_name: "x346hbmv"
      LaunchTemplateName: GRIMTemplate  
  GRIMCompute:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: GRIMCompute
      ComputeResources: 
        AllocationStrategy: BEST_FIT
        DesiredvCpus: 8
        Ec2KeyPair: awsoregon
        InstanceRole: arn:aws:iam::378722409401:instance-profile/ecsInstanceRole
        InstanceTypes:
          - p3
        LaunchTemplate:
          LaunchTemplateId: !Ref GRIMLaunchTemplate
          Version: $Default
        MaxvCpus: 256
        MinvCpus: 0
        SecurityGroupIds:
          - sg-b3f854c8
        Subnets:
          - subnet-7979c31c
        Type: EC2
      ServiceRole: arn:aws:iam::378722409401:role/service-role/AWSBatchServiceRole
      State: ENABLED
      Type: MANAGED
  GRIMJobQueue:
    Type: AWS::Batch::JobQueue
    Properties: 
      ComputeEnvironmentOrder: 
        - ComputeEnvironment: !Ref GRIMCompute
          Order: 1
      Priority: 1
      JobQueueName: GRIMJobQueue
      State: ENABLED
  GRIMJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties: 
      ContainerProperties: 
        Command:
          - ./grim
        Environment:
          - Name: FEM_REPO
            Value: /fsx/20220308_1335_MT_mount_zen_30_m1HFN_FSM/
          - Name: CFD_REPO
            Value: /fsx/CASES
          - Name: DATA_REPO
            Value: /fsx/grim
          - Name: M1CALIBRATION
            Value: /fsx/m1calibration/
          - Name: GMT_MODES_PATH
            Value: /fsx/ceo/
          - Name: SH48_N_STEP
            Value: 10
          - Name: LOM
            Value: /fsx
          - Name: WITH_ATMOSPHERE
            Value: ON          
          - Name: WITH_DOME_SEEING
            Value: ON          
          - Name: WITH_STATIC_ABERRATION
            Value: /fsx/ceo/raw-polishing_print-through_769.bin
        Image: 378722409401.dkr.ecr.us-west-2.amazonaws.com/gmto.im/grim:latest
        ResourceRequirements:
          - Type: VCPU
            Value: '8'
          - Type: MEMORY
            Value: '50000'
          - Type: GPU
            Value: '1'
        MountPoints:
          - ContainerPath: /fsx
            SourceVolume: fsx
        Volumes:
          - Host:
              SourcePath: /fsx
            Name: fsx        
      JobDefinitionName: GRIMJob
      PlatformCapabilities: 
        - EC2
      Type: container
